In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [2]:
x = np.arange(10).reshape(-1,1)

In [3]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
y = np.array([0,1,0,0,1,1,1,1,1,1])
y

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

In [5]:
model = LogisticRegression().fit(x,y)

In [6]:
score = model.score(x,y)

In [7]:
score

0.8

In [8]:
y_pred = model.predict(x)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])