Loading numpy

In [63]:
import numpy as np

In [62]:
# a = np.array([1,2,3],  dtype='int32')
# print (a) #1 dimensional

In [60]:
# b = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]])
# print(b) #2 dimensional

In [61]:
# c = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0],[23,45,67]])
# print(c) #2 dimensional

In [48]:
#get dimension
# a.ndim
# b.ndim
# c.ndim


In [49]:
#get shape
# a.shape
# b.shape
# c.shape

In [50]:
# get type
# a.dtype
# b.dtype
# c.dtype


In [51]:
# get size
# a.itemsize   #smaller
# b.itemsize   #bigger
# c.itemsize

In [55]:
# get total size
# a.nbytes
# b.nbytes
# c.nbytes

Accessing/changing specific elements

In [64]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [70]:
#  a.shape

In [71]:
#get a specific element[row-index, column-index]
a[1, 5]

13

In [74]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [76]:
#get a specific column
a[:,2]

array([ 3, 10])

In [80]:
#getting a lot more fancy [startindex:stopindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [81]:
a[1,5] = 20

In [84]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [85]:
a[:,2] = 5

In [86]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
